### ISSUE TITLE
When I run the server from OVA on VMware I'm getting the SSH ports

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder-bugs#9] opened 2021-05-17 19:04 UTC
@kekesimarti commented on [Thu May 06 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/285)

![image.png](https://images.zenhubusercontent.com/6033d6c0a356dc6005080557/e724e992-4399-46e7-9423-6c84039bba5c)

**Comment by MaNe2020** [comment] 2021-06-30 07:18
Will close this as a duplicate of https://github.com/filetrust/cdr-plugin-folder-to-folder-bugs/issues/12

**Closed** 2021-06-30 07:18 UTC
Labels: Esxi, P3
