### ISSUE TITLE
Running server (on latest OVA) doesn't not have any logs

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder-bugs#10] opened 2021-05-17 19:04 UTC
@kekesimarti commented on [Thu May 06 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/287)

![image](https://user-images.githubusercontent.com/79467690/117276037-f1186a00-ae5e-11eb-9c66-656fb616efba.png)

**Comment by MaNe2020** [comment] 2021-05-21 12:39
This seems to be working. 
![image](https://user-images.githubusercontent.com/70108899/119138557-4ac58a80-ba42-11eb-9a95-90beaa20a3b4.png)

In general it can happened that indexes are not loaded correctly. In that case best is to do `docker-compose down` and `docker-compose up --build --force`

Will close this one as I cannot reproduce it.

**Closed** 2021-05-21 12:39 UTC
Labels: Esxi
