### ISSUE TITLE
Pressing "load files" a newly deployed AMI causes 500: Internal Server Error

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder-bugs#20] opened 2021-05-17 19:09 UTC
@ggrig commented on [Thu May 06 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/292)

![image](https://user-images.githubusercontent.com/26714598/117309697-b7ae2180-ae93-11eb-9cb3-d282594287e5.png)

---

@GINAGC commented on [Wed May 12 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/292#issuecomment-839493234)

@ggrig, @MaNe2020 is this still an issue?

---

@MaNe2020 commented on [Wed May 12 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/292#issuecomment-839701773)

@ggrig do you remember what were the steps you executed? 
I think it was click LOAD before CLEANING the folder? I can retry to verify

**Comment by MaNe2020** [comment] 2021-05-21 14:19
Will close this one as I am not able to reproducer it. 
@ggrig if this happens again pls add exact steps.

**Comment by kekesimarti** [comment] 2021-05-28 10:19
I'm reopening this as we found a way to reproduce and found it again in v0.8.8

**Comment by MaNe2020** [comment] 2021-06-08 07:04
It is needed, whoever finds this to add exact steps!
Without step we cannot do verification/fix on this.

**Comment by MaNe2020** [comment] 2021-06-30 07:36
Will close this one as we have new UI in place. If similar happens will open new issue.

**Closed by MaNe2020** 2021-06-30 07:36 UTC
Labels: P2, need-more-info
